### ISSUE TITLE
Close button does not show in header if we add actionButtons.

### ISSUE THREAD

**Issue by onkarjanwa** [Greentube/ngx-modal#44] opened 2018-11-03 09:58 UTC
Here is my code.

> this.modalService.openDialog(this.viewRef, {
            title: 'Add Delivery Address',
            childComponent: OrderPageModelComponent,
            settings: {
                closeButtonClass: 'btn fa fa-times text-muted bg-white p-0 mt-2',
            },
            actionButtons: [
              { text: 'Continue', onAction: () => true, buttonClass: 'btn btn-success' }
            ]
        });

If i remove **actionButtons**  property then it does not show close icon in right top.

I am working on Angular7.

**Comment by meeroslav** [comment] 2018-11-07 20:50
This is by design... 

There are two modes of the modal dialog:
1. An info dialog - that can be closed via the close button in the header or
2. A prompt dialog - that requires an action from the user

Idea was, that if you already have an action, it's more natural to place "Close" or "Cancel" or "No" button next to it.

If this doesn't satisfy your requirements, maybe you can share your use case details.

**Comment by meeroslav** [comment] 2018-11-07 20:54
Duplicate of #41

**Closed by meeroslav** 2018-11-07 20:54 UTC
Labels: question
